---
title: "Geomap"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## This paragraph for Geomap

```{r}
library(ggplot2)
# read data
pollution_month <- read.csv("Pollution.csv")
head(pollution_month)
```

```{r}
# filter the pollutant
particles <- pollution_month$CA + pollution_month$MG + pollution_month$NA. +
  pollution_month$K
main_pollutant <- data.frame(pollution_month$STATE, pollution_month$TIME, 
                        pollution_month$YEAR, pollution_month$MONTH)
main_pollutant$Particles <- particles
main_pollutant$SO2 <- pollution_month$TOTAL_SO2
main_pollutant$NO3 <- pollution_month$TOTAL_NO3
colnames(main_pollutant) <- c("State", "Time", "Year", "Month", "Particles", "SO2", "NO3")
# see the structure of "main_pollutant"
head(main_pollutant)
write.csv(main_pollutant, file = "main_pollutant.csv")
```




```{r}
# preprocess SO2
Particles_mean <- aggregate(Particles~State, main_pollutant, mean)
SO2_mean <- aggregate(SO2~State, main_pollutant, mean)
NO3_mean <- aggregate(NO3~State, main_pollutant, mean)
colnames(Particles_mean) <- c("state", "Particles")
colnames(SO2_mean) <- c("state", "SO2")
colnames(NO3_mean) <- c("state", "NO3")
pollutant_mean <- merge(Particles_mean, SO2_mean)
pollutant_mean <- merge(pollutant_mean, NO3_mean)
head(pollutant_mean)
```


```{r}

ggplot(SO2_mean, aes(x = SO2, y = reorder(state, SO2))) + 
  geom_point(color = "orange") + 
  xlab("Mean SO2") + ylab("") + 
  ggtitle("Cleveland Dot Plot of SO2 by State") + 
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))

```
```{r results='hide', message=FALSE, warning=FALSE, fig.height=7, fig.width=6, fig.align='center'}
library(micromap)
data("USstates")
statePolys <- create_map_table(USstates, IDcolumn = "ST")

lmplot(stat.data = pollutant_mean,
       map.data = statePolys,
       panel.types = c('dot_legend', 'labels', 'dot', 'map'),
       panel.data = list(NA, 'state','Particles', NA),
       ord.by = 'Particles', 
       rev.ord = TRUE,
       grouping = 5,
       colors = brewer.pal(5, "Set1"),
       median.row = TRUE,
       map.link = c('state', 'ID'),
       # how to merge the two data frames:
       map.color2 = "white",
       # attributes of the panels:
       panel.att = list(
         list(1, point.type=20,
              point.border=TRUE),
          list(2, header = "States",
               panel.width = 0.2,
               panel.header.face = "bold",
               panel.header.size = 1.2,
               graph.grid.color = "grey99",
               align = "left"),
          list(3, header = "Particles Pollution Amount", 
               panel.header.face = "bold",
               panel.header.size = 1.2,
               xaxis.title = 'ug/m^3'),
          list(4, header = 'Geographical Location',
               panel.header.face = "bold",
               panel.header.size = 1.2)
          ))

```

```{r results='hide', message=FALSE, warning=FALSE, fig.height=7, fig.width=6, fig.align='center'}
statePolys <- create_map_table(USstates, IDcolumn = "ST")

lmplot(stat.data = pollutant_mean,
       map.data = statePolys,
       panel.types = c('dot_legend', 'labels', 'dot', 'map'),
       panel.data = list(NA, 'state','SO2', NA),
       ord.by = 'SO2', 
       rev.ord = TRUE,
       grouping = 5,
       colors = brewer.pal(5, "Set1"),
       median.row = TRUE,
       map.link = c('state', 'ID'),
       # how to merge the two data frames:
       map.color2 = "white",
       # attributes of the panels:
       panel.att = list(
         list(1, point.type=20,
              point.border=TRUE),
          list(2, header = "States",
               panel.width = 0.2,
               panel.header.face = "bold",
               panel.header.size = 1.2,
               graph.grid.color = "grey99",
               align = "left"),
          list(3, header = "SO2 Pollution Amount", 
               panel.header.face = "bold",
               panel.header.size = 1.2,
               xaxis.title = 'ug/m^3'),
          list(4, header = 'Geographical Location',
               panel.header.face = "bold",
               panel.header.size = 1.2)
          ))

```
```{r results='hide', message=FALSE, warning=FALSE, fig.height=7, fig.width=6, fig.align='center'}
statePolys <- create_map_table(USstates, IDcolumn = "ST")

lmplot(stat.data = pollutant_mean,
       map.data = statePolys,
       panel.types = c('dot_legend', 'labels', 'dot', 'map'),
       panel.data = list(NA, 'state','NO3', NA),
       ord.by = 'NO3', 
       rev.ord = TRUE,
       grouping = 5,
       colors = brewer.pal(5, "Set1"),
       median.row = TRUE,
       map.link = c('state', 'ID'),
       # how to merge the two data frames:
       map.color2 = "white",
       # attributes of the panels:
       panel.att = list(
         list(1, point.type=20,
              point.border=TRUE),
          list(2, header = "States",
               panel.width = 0.2,
               panel.header.face = "bold",
               panel.header.size = 1.2,
               graph.grid.color = "grey99",
               align = "left"),
          list(3, header = "NO3 Pollution Amount", 
               panel.header.face = "bold",
               panel.header.size = 1.2,
               xaxis.title = 'ug/m^3'),
          list(4, header = 'Geographical Location',
               panel.header.face = "bold",
               panel.header.size = 1.2)
          ))

```